// app/harness/src/salvage-corpus.ts
// A CORPUS OF GENUINELY DAMAGED SQLite FILES, as a deterministic byte-exact
// generator.
//
// 051 graded salvage against a healthy file, a scripted row-and-file-level
// injury and a zero-byte file, and recorded the hole in its own write-back: the
// gap between "valid file, damaged rows" and "not a database at all" -- a
// truncated write, a torn page, a lost WAL -- is the state a writer with a
// genuinely broken book is most likely in, and nothing in this repo had ever
// produced one. Every recovery path in `salvage.rs` was built and graded against
// damage inflicted THROUGH SQL, on a file SQLite still considers valid.
//
// DETERMINISM IS THE REQUIREMENT, not a nicety. A corpus generated by a seeded,
// byte-exact procedure is evidence; one that mutates a file at random is an
// anecdote nobody can re-run. Every function here is pure: bytes in, bytes out,
// no clock, no randomness, no filesystem. `salvage-corpus.test.ts` asserts two
// independent generations agree byte for byte and that the truncation entries
// are the prefixes the test computes for itself.
//
// IT IS A MODULE AND NOT A BLOCK INSIDE `salvage-cli.ts`, for the recorded
// reason: a rule written inside a `*-cli.ts` is unmutatable, because those files
// abort at module scope and no test can import them.
//
// NOTHING HERE WRITES SQLite. Every entry is a transform of a file SQLite itself
// wrote -- a prefix of it, one page of it replaced, four bytes of a header or a
// b-tree cell moved. That is the line the slice was given and it is also the
// only honest one: a corpus this harness ENCODED would be graded against this
// harness's idea of the format rather than against SQLite's.

/** The SQLite file header: 100 bytes, and page 1's own b-tree header follows
 *  it. Offsets below are the format's, and are the only thing this module knows
 *  about SQLite that it did not read out of a file SQLite wrote. */
export const HEADER_BYTES = 100;
const MAGIC = "SQLite format 3\0";
/** Bytes 16..18: the page size, with 1 meaning 65536. */
const OFF_PAGE_SIZE = 16;
/** Bytes 24..28: the file change counter. */
const OFF_CHANGE_COUNTER = 24;
/** Bytes 28..32: the database size in pages, as the header claims it. */
const OFF_PAGE_COUNT = 28;
/** Bytes 92..96: the change-counter value the size at 28 was valid for. When
 *  the two disagree, SQLite distrusts the size and measures the file instead. */
const OFF_VERSION_VALID_FOR = 92;
/** Page type bytes. 2 and 5 are interior pages and carry a rightmost child
 *  pointer in a twelve-byte header; 10 and 13 are leaves with an eight-byte
 *  one. */
const INTERIOR_INDEX = 2;
const INTERIOR_TABLE = 5;

function view(bytes: Uint8Array): DataView {
  return new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
}

function requireHeader(bytes: Uint8Array): DataView {
  if (bytes.length < HEADER_BYTES) {
    throw new Error(`not a SQLite file: ${bytes.length} byte(s), shorter than the 100-byte header`);
  }
  const magic = new TextDecoder("latin1").decode(bytes.subarray(0, MAGIC.length));
  if (magic !== MAGIC) throw new Error("not a SQLite file: the header magic is not present");
  return view(bytes);
}

export function pageSize(bytes: Uint8Array): number {
  const raw = requireHeader(bytes).getUint16(OFF_PAGE_SIZE);
  return raw === 1 ? 65536 : raw;
}

export function headerPageCount(bytes: Uint8Array): number {
  return requireHeader(bytes).getUint32(OFF_PAGE_COUNT);
}

export function changeCounter(bytes: Uint8Array): number {
  return requireHeader(bytes).getUint32(OFF_CHANGE_COUNTER);
}

export function versionValidFor(bytes: Uint8Array): number {
  return requireHeader(bytes).getUint32(OFF_VERSION_VALID_FOR);
}

/** Every page of one b-tree, root first and the rest in SCAN ORDER.
 *
 *  IN SCAN ORDER, because the corpus tears a page out of the middle of a tree
 *  and what makes that injury interesting is that a cursor reaches rows BEFORE
 *  it dies. A breadth-first list would put the torn page somewhere arbitrary in
 *  the traversal and the same generator would produce a different injury on a
 *  differently shaped tree.
 *
 *  A page already seen is skipped rather than followed: a corpus entry that
 *  broke a child pointer into a cycle would otherwise hang the generator, and a
 *  generator that hangs on its own output is not a generator. */
export function btreePages(bytes: Uint8Array, root: number): number[] {
  const ps = pageSize(bytes);
  const dv = view(bytes);
  const out: number[] = [];
  const seen = new Set<number>();
  const visit = (page: number): void => {
    if (page < 1 || seen.has(page)) return;
    const base = (page - 1) * ps;
    if (base + ps > bytes.length) return;
    seen.add(page);
    out.push(page);
    const h = base + (page === 1 ? HEADER_BYTES : 0);
    const type = bytes[h]!;
    if (type !== INTERIOR_INDEX && type !== INTERIOR_TABLE) return;
    const cells = dv.getUint16(h + 3);
    for (let i = 0; i < cells; i++) {
      const off = dv.getUint16(h + 12 + i * 2);
      if (base + off + 4 > bytes.length) continue;
      visit(dv.getUint32(base + off));
    }
    visit(dv.getUint32(h + 8));
  };
  visit(root);
  return out;
}

function requirePage(bytes: Uint8Array, page: number): { ps: number; at: number } {
  const ps = pageSize(bytes);
  const at = (page - 1) * ps;
  if (page < 1 || at + ps > bytes.length) {
    throw new Error(`page ${page} is not in this file (${bytes.length / ps} page(s) of ${ps})`);
  }
  return { ps, at };
}

export function truncateTo(bytes: Uint8Array, length: number): Uint8Array {
  return bytes.slice(0, length);
}

/** One page replaced with zeros: the page that never reached the platter, and
 *  the block a filesystem hands back as a hole. Byte 0 of a page is its type,
 *  and 0 is not one, so SQLite calls the file malformed the moment it reads
 *  it. */
export function zeroPage(bytes: Uint8Array, page: number): Uint8Array {
  return overwritePage(bytes, page, 0);
}

/** One page replaced with a repeating byte: a block from somewhere else on the
 *  disk landing here, which fails differently from a hole because the page
 *  header parses into nonsense rather than into nothing. */
export function overwritePage(bytes: Uint8Array, page: number, fill: number): Uint8Array {
  const { ps, at } = requirePage(bytes, page);
  const out = bytes.slice();
  out.fill(fill, at, at + ps);
  return out;
}

export function setPageSizeField(bytes: Uint8Array, size: number): Uint8Array {
  const out = bytes.slice();
  view(out).setUint16(OFF_PAGE_SIZE, size === 65536 ? 1 : size);
  return out;
}

/** The four-byte left-child pointer of one cell on an INTERIOR page. Bit rot in
 *  a b-tree interior cell, which is the one damage that sends a cursor to a page
 *  that has nothing to do with the tree it is walking. */
export function setChildPointer(
  bytes: Uint8Array,
  page: number,
  cell: number,
  child: number,
): Uint8Array {
  const { at } = requirePage(bytes, page);
  const h = at + (page === 1 ? HEADER_BYTES : 0);
  const dv = view(bytes);
  const cells = dv.getUint16(h + 3);
  if (cell >= cells) throw new Error(`page ${page} holds ${cells} cell(s); there is no cell ${cell}`);
  const off = dv.getUint16(h + 12 + cell * 2);
  const out = bytes.slice();
  view(out).setUint32(at + off, child);
  return out;
}

/** THE REPAIR THIS CORPUS EXPECTS SALVAGE TO MAKE, restated here as the harness
 *  restates every threshold -- it is NOT imported from `salvage.rs` and the two
 *  are free to drift, which is the point.
 *
 *  SQLite trusts the page count at byte 28 only while the number at byte 92 says
 *  which change-counter value it was computed for. Move them apart and SQLite
 *  measures the file instead, which is exactly the right answer for a file whose
 *  tail is gone. Returns null when the header does not overclaim (nothing to
 *  repair) or is already distrusted (nothing to do). */
export function distrustHeaderPageCount(bytes: Uint8Array): Uint8Array | null {
  const ps = pageSize(bytes);
  const claimed = headerPageCount(bytes);
  const actual = Math.floor(bytes.length / ps);
  if (claimed <= actual) return null;
  const counter = changeCounter(bytes);
  if (versionValidFor(bytes) !== counter) return null;
  const out = bytes.slice();
  view(out).setUint32(OFF_VERSION_VALID_FOR, (counter + 1) >>> 0);
  return out;
}

export function digest(bytes: Uint8Array): string {
  return new Bun.CryptoHasher("sha256").update(bytes).digest("hex");
}

/** The two b-tree roots the corpus tears a page out of, by rootpage number.
 *
 *  THEY ARE PASSED IN AND NOT LOOKED UP, because which b-tree a rowid
 *  enumeration actually scans is a question for `EXPLAIN QUERY PLAN` against the
 *  file, not for this module -- and every table in this schema answers
 *  `SELECT rowid FROM <t>` through a COVERING INDEX rather than through the
 *  table. Tearing a page out of the `item` TABLE would never stop an
 *  enumeration; tearing one out of `sqlite_autoindex_item_1` does. The rig
 *  measures the plan and passes the root it names. */
export interface CorpusTargets {
  /** The b-tree `SELECT rowid FROM item` is answered by. */
  enumerationIndexRoot: number;
  /** The `doc` table's own b-tree: where the prose lives, and the tree a row
   *  fetch by rowid reads. */
  documentTableRoot: number;
}

export interface CorpusEntry {
  name: string;
  /** What was done to the bytes, exactly. */
  injury: string;
  /** The accident a writer has that produces this file. */
  represents: string;
  /** The exit codes this file may legitimately produce. 1 is never among them:
   *  1 is the operator asking wrongly and has nothing to do with the source. */
  allowedExits: number[];
  db: Uint8Array;
  /** The `-wal` sidecar to write beside it, or null for the ordinary case. */
  wal: Uint8Array | null;
}

/** How much of the file the tail-loss entries keep. Nine tenths: enough that
 *  SQLite still parses the schema once the header is distrusted, so the entry
 *  grades a PARTIAL recovery rather than a refusal. */
const TAIL_KEPT = 0.9;
/** The byte the overwritten page is filled with. Any non-zero constant; 0xa5 is
 *  the one a person reading a hex dump recognises as deliberate. */
const GARBAGE_BYTE = 0xa5;
/** A page number no file in this corpus has. */
const NOWHERE = 999_999;
/** The page size the lying header claims. A legal SQLite page size, so the
 *  header stays well-formed and only the geometry is wrong -- a header claiming
 *  an ILLEGAL size is rejected as "not a database" and grades the same path the
 *  zero-byte source already grades. */
const LIED_PAGE_SIZE = 512;

/** The page of a tree to tear: the MIDDLE of its scan order, so a cursor has
 *  read rows before it dies, and the root when the tree is a single page. */
export function tornPageOf(pages: number[]): number {
  return pages[Math.floor(pages.length / 2)] ?? pages[0]!;
}

export function corpusPlan(base: Uint8Array, targets: CorpusTargets): CorpusEntry[] {
  const ps = pageSize(base);
  // A VACUITY GUARD, and it fired the first time this file was run: the
  // page-size entry is a no-op on a base whose pages are already that size, and
  // a corpus entry byte-identical to the healthy file grades the healthy path
  // while claiming to grade a lie.
  if (ps === LIED_PAGE_SIZE) {
    throw new Error(
      `this file's pages are already ${LIED_PAGE_SIZE} bytes, so header_page_size_lie would ` +
        "produce the healthy file unchanged and grade nothing",
    );
  }
  const pages = Math.floor(base.length / ps);
  const keep = Math.max(1, Math.floor(pages * TAIL_KEPT));
  const indexTree = btreePages(base, targets.enumerationIndexRoot);
  const docTree = btreePages(base, targets.documentTableRoot);
  const tornIndexPage = tornPageOf(indexTree);
  const tornDocPage = docTree[docTree.length - 1]!;
  const interior = docTree[0]!;

  const entries: CorpusEntry[] = [
    {
      name: "header_torn",
      injury: "the file is 60 bytes long: the 100-byte SQLite header itself is cut in half",
      represents:
        "the write that never got past the header, and the copy that died in its first block",
      allowedExits: [2],
      db: truncateTo(base, 60),
      wal: null,
    },
    {
      name: "tail_lost_at_page_boundary",
      injury: `the last ${pages - keep} of ${pages} pages are gone; the header still claims ${pages}`,
      represents: "a book copied off a dying disk, or a write interrupted before the tail landed",
      allowedExits: [2, 3],
      db: truncateTo(base, keep * ps),
      wal: null,
    },
    {
      name: "tail_lost_mid_page",
      injury: `the file ends ${Math.floor(ps / 3)} bytes into page ${keep + 1}, so the last page is a fragment`,
      represents: "the laptop that lost power in the middle of a page write",
      allowedExits: [2, 3],
      db: truncateTo(base, keep * ps + Math.floor(ps / 3)),
      wal: null,
    },
    {
      name: "torn_page_zeroed",
      injury: `page ${tornIndexPage} of the b-tree a rowid enumeration scans is all zeros`,
      represents:
        "a page that never reached the platter: the filesystem hands back a hole where the " +
        "index used to be, and the enumeration of a whole table dies part way through",
      allowedExits: [2, 3],
      db: zeroPage(base, tornIndexPage),
      wal: null,
    },
    {
      name: "torn_page_overwritten",
      injury: `page ${tornDocPage} of the doc table holds 0x${GARBAGE_BYTE.toString(16)} repeated`,
      represents:
        "a block from somewhere else on the disk landing on the prose: the page header parses " +
        "into nonsense rather than into nothing",
      allowedExits: [2, 3],
      db: overwritePage(base, tornDocPage, GARBAGE_BYTE),
      wal: null,
    },
    {
      name: "header_page_size_lie",
      injury: `the header says the pages are ${LIED_PAGE_SIZE} bytes and they are ${ps}`,
      represents: "a torn header block: the file's geometry is described by a number that is wrong",
      allowedExits: [2, 3],
      db: setPageSizeField(base, LIED_PAGE_SIZE),
      wal: null,
    },
    {
      name: "broken_interior_pointer",
      injury: `the first child pointer of page ${interior} points at page ${NOWHERE}`,
      represents: "bit rot in a b-tree interior cell: the cursor is sent somewhere that is not there",
      allowedExits: [2, 3],
      db: setChildPointer(base, interior, 0, NOWHERE),
      wal: null,
    },
    {
      name: "orphaned_wal",
      injury:
        "the database is untouched and a -wal sidecar of repeating bytes sits beside it, with " +
        "neither a valid WAL header nor a frame checksum that could be recovered",
      represents:
        "the crash before the checkpoint, where what is left of the write-ahead log is not " +
        "something SQLite can replay",
      allowedExits: [0, 2, 3],
      db: base.slice(),
      wal: new Uint8Array(ps * 2).fill(GARBAGE_BYTE),
    },
  ];
  return entries;
}
